// <auto-generated />
using BusinessCardHolder.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessCardHolder.Migrations
{
    [DbContext(typeof(BusinessCardHolderContext))]
    partial class BusinessCardHolderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusinessCardHolder.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(345);

                    b.Property<int>("FirmId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(55);

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(1075);

                    b.Property<string>("MobileTelephone")
                        .IsRequired()
                        .HasMaxLength(18);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(18);

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BusinessCardHolder.Models.Firm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(105);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(180);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(345);

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasMaxLength(13);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(155);

                    b.Property<string>("Notes");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(18);

                    b.HasKey("Id");

                    b.ToTable("Firms");
                });

            modelBuilder.Entity("BusinessCardHolder.Models.Employee", b =>
                {
                    b.HasOne("BusinessCardHolder.Models.Firm", "Firm")
                        .WithMany("Employees")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
